"""
Memory-aware research orchestration.

Coordinates Cohort 2 response generation, memory retrieval, and the
Cohort 3 evaluator-optimizer workflow.

Cohort 2 owns initial response generation through its router service.
Cohort 3 owns evaluation, reflection, optimization, and persistence.
"""

from __future__ import annotations

from typing import Protocol

from evaluator_optimizer.config import DEFAULT_MEMORY_MAX_RESULTS
from evaluator_optimizer.logging_config import get_logger
from evaluator_optimizer.memory.context import MemoryContext
from evaluator_optimizer.memory.memory_builder import MemoryBuilder
from evaluator_optimizer.memory.memory_service import MemoryService
from evaluator_optimizer.memory.repository import MemoryQuery
from evaluator_optimizer.optimization.optimization_controller import (
    OptimizationController,
)
from evaluator_optimizer.orchestration.evaluation_trace import (
    EvaluationTrace,
)


logger = get_logger("orchestration.memory_aware")


class ResearchRouterService(Protocol):
    """Cohort 2 router contract required by Cohort 3."""

    def route(self, query: str, context: str) -> str:
        """Return the initial response generated by the routed specialist."""
        ...


class MemoryAwareResearchService:
    """Coordinate Cohort 2 generation with Cohort 3 optimization and memory."""

    def __init__(
        self,
        router_service: ResearchRouterService,
        memory_service: MemoryService,
        memory_builder: MemoryBuilder,
        optimization_controller: OptimizationController,
    ) -> None:
        self._router_service = router_service
        self._memory_service = memory_service
        self._memory_builder = memory_builder
        self._optimization_controller = optimization_controller

    def run(
        self,
        exchange_symbol: str,
        query: str,
        context: str,
        topics: list[str] | None = None,
    ) -> tuple[EvaluationTrace, MemoryContext]:
        """
        Generate the initial response through Cohort 2 and optimize it.

        ``answer`` is intentionally not accepted from the caller. This
        prevents the integration layer from bypassing the Cohort 2
        routing/generation workflow.
        """
        logger.info(
            "Memory-aware workflow started | symbol=%s",
            exchange_symbol,
        )

        memory_context = self.retrieve_memory(
            exchange_symbol=exchange_symbol,
            query=query,
            topics=topics or [],
        )

        initial_response = self._router_service.route(
            query=query,
            context=context,
        )

        logger.info(
            "Initial response generated by Cohort 2 router | symbol=%s",
            exchange_symbol,
        )

        trace = self._optimization_controller.run(
            query=query,
            answer=initial_response,
            context=context,
        )

        trace.record_memory_retrieved(
            [memory.memory_id for memory in memory_context.memories]
        )

        final_answer = trace.optimized_answer or trace.initial_answer

        memory = self._memory_builder.build(
            exchange_symbol=exchange_symbol,
            query=query,
            research_summary=final_answer,
            key_findings=[],
            claims=[],
            evidence=[],
            identified_gaps=memory_context.research_gaps,
            evaluation_results=trace.final_evaluation,
            topics=topics,
        )

        self._memory_service.save(memory)

        trace.record_memory_applied(
            [memory_item.memory_id for memory_item in memory_context.memories]
        )

        logger.info(
            "Memory-aware workflow completed | retrieved=%d | applied=%d",
            len(trace.memory_retrieved),
            len(trace.memory_applied),
        )

        return trace, memory_context

    def retrieve_memory(
        self,
        exchange_symbol: str,
        query: str,
        topics: list[str],
    ) -> MemoryContext:
        """Retrieve relevant memories for a research request."""
        query_signature = self._memory_builder.create_query_signature(query)

        results = self._memory_service.search(
            MemoryQuery(
                exchange_symbol=exchange_symbol,
                topics=topics,
                query_signature=query_signature,
                query_text=None,
                max_results=DEFAULT_MEMORY_MAX_RESULTS,
            )
        )

        context = MemoryContext()

        for memory in results:
            context.add_memory(memory)

            for gap in memory.identified_gaps:
                context.add_research_gap(gap)

        return context
